[package]
name = "switch_switch"
version = "0.1.0"
authors = ["Andrii Kapinos <broxbeats@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
